Issue 3
rotsuya/otsubot pull request #20
Opened 2018-10-16 01:00 UTC by ShinyaFUKUMOTO

Add remove command into otsubot. Any user can remove a record from a specified user’s timecard by this command.

Refs #3 

Results of Manual tests in localhost are as follows:
```
otsubot> hi 10/16 9
otsubot> おはようございます。Shellの2018/10/16の勤務時間は09:00~だね。

otsubot> bye 10/16 18
otsubot> お疲れさま。Shellの2018/10/16の勤務時間は~18:00だね。

otsubot> hi 10/17 10
otsubot> おはようございます。Shellの2018/10/17の勤務時間は10:00~だね。

otsubot> bye 10/17 20
otsubot> 乙。Shellの2018/10/17の勤務時間は~20:00だね。

otsubot> list
otsubot> Shellの10月の勤務表だね。
```date       | recorded      | calculated    | overtime
2018/10/16 | 09:00 | 18:00 | 09:00 | 18:00 | 00:30
2018/10/17 | 10:00 | 20:00 | 10:00 | 20:00 | 01:30
sum        |       |       |       |       | 02:00```

otsubot> rm 1017
otsubot> Shellの2018/10/17の勤務記録を削除だね。

otsubot> list
otsubot> Shellの10月の勤務表だね。
```date       | recorded      | calculated    | overtime
2018/10/16 | 09:00 | 18:00 | 09:00 | 18:00 | 00:30
sum        |       |       |       |       | 00:30```
```

2018-10-24 06:41 UTC, rotsuya commented
Thanks! I'll test and merge tomorrow!

2018-10-25 00:03 UTC, rotsuya requested changes

2018-10-25 00:03 UTC, rotsuya commented on scripts/otsubot.js
> +        robot.brain.remove(JSON.stringify(key), value);
Please remove 2nd argument because `brain.remove` needs only one argument.

2018-10-25 02:14 UTC, ShinyaFUKUMOTO commented
The unnecessary parameter was removed.
This commit passed the same tests as above in my environment.

2020-04-20 03:25 UTC, merged